### ISSUE TITLE
Use of `tokio-file-unix` breaks compilation on Windows

### ISSUE THREAD

**Issue by Michael-F-Bryan** [asonix/tokio-zmq#11]
I just tried building `tokio-zmq` on a Windows machine and it looks like we unconditionally depend on `tokio-file-unix`, which obviously causes compilation to fail.

How difficult would it be to use [platform-specific dependencies] in `Cargo.toml` and then add the necessary `#[cfg(unix)]` attributes to skip file operations on Windows?

```toml
# Cargo.toml

[target.'cfg(unix)'.dependencies]
tokio-file-unix = "0.5"
```

[platform-specific dependencies]: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies
